name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/containerfs-ci:latest
            ghcr.io/${{ github.repository_owner }}/containerfs-ci:${{ github.sha }}

      - name: Test using published image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/containerfs-ci:latest
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/${{ github.repository_owner }}/containerfs-ci:latest cmake --workflow --preset release

