name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/containerfs-ci:latest
            ghcr.io/${{ github.repository_owner }}/containerfs-ci:${{ github.sha }}

      - name: Pull published image
        run: docker pull ghcr.io/${{ github.repository_owner }}/containerfs-ci:latest

      - name: Run tests in container
        run: docker run --rm ghcr.io/${{ github.repository_owner }}/containerfs-ci:latest
